name: Publish NPM Package
on:
  # 推送到 main 分支时触发（适合持续发布）
  push:
    branches: [main]
    paths:
      - "package.json" # 只有当 package.json 变化时才触发

  # 创建 Release 时触发（适合版本发布）
  release:
    types: [published]

  # 手动触发
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      # 安装依赖
      - run: npm ci

      # 运行测试（如果有）
      # - run: npm test

      # 构建项目（如果需要）
      # - run: npm run build

      # 发布到 npm
      - run: npm publish --tag latest --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 构建 Storybook（如果你的项目有）
      - run: npm run build-storybook
        continue-on-error: true # 如果没有 storybook 就跳过

      - uses: actions/upload-pages-artifact@v4
        if: success()
        with:
          path: storybook-static

      - id: deploy
        uses: actions/deploy-pages@v4
        if: success()
        with:
          token: ${{ github.token }}
